services:
  cpsl_sensors:
    image: cpsl_sensors:gpu
    container_name: cpsl_sensors_gpu
    ipc: host
    environment:
      - ROS_DOMAIN_ID=42
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all,graphics,utility,compute
    ports:
      # TI Radar DCA1000 Streaming Port Forwarding
      - "${HOST_RADAR_IP:-192.168.33.30}:4096:4096/udp"
      - "${HOST_RADAR_IP:-192.168.33.30}:4098:4098/udp"
      # Livox Mid360 Lidar Port Forwarding
      - "${HOST_LIVOX_IP:-192.168.1.78}:56101:56101/udp"
      - "${HOST_LIVOX_IP:-192.168.1.78}:56201:56201/udp"
      - "${HOST_LIVOX_IP:-192.168.1.78}:56301:56301/udp"
      - "${HOST_LIVOX_IP:-192.168.1.78}:56401:56401/udp"
      # Ouster Lidar Port Forwarding
      - "${HOST_OUSTER_IP:-169.254.1.1}:7502:7502/udp"
      - "${HOST_OUSTER_IP:-169.254.1.1}:7503:7503/udp"
    devices:
      # TI Radars Serial Interfaces (Role Mapped)
      - "${FRONT_RADAR_CLI:-/dev/null}:${FRONT_RADAR_CLI:-/dev/null}"
      - "${FRONT_RADAR_DATA:-/dev/null}:${FRONT_RADAR_DATA:-/dev/null}"
      - "${BACK_RADAR_CLI:-/dev/null}:${BACK_RADAR_CLI:-/dev/null}"
      - "${BACK_RADAR_DATA:-/dev/null}:${BACK_RADAR_DATA:-/dev/null}"
      - "${DOWN_RADAR_CLI:-/dev/null}:${DOWN_RADAR_CLI:-/dev/null}"
      - "${DOWN_RADAR_DATA:-/dev/null}:${DOWN_RADAR_DATA:-/dev/null}"
      # Intel RealSense Camera Video Devices
      - "${REALSENSE_DEV_0:-/dev/null}:${REALSENSE_DEV_0:-/dev/null}"
      - "${REALSENSE_DEV_1:-/dev/null}:${REALSENSE_DEV_1:-/dev/null}"
      - "${REALSENSE_DEV_2:-/dev/null}:${REALSENSE_DEV_2:-/dev/null}"
      - "${REALSENSE_DEV_3:-/dev/null}:${REALSENSE_DEV_3:-/dev/null}"
      - "${REALSENSE_DEV_4:-/dev/null}:${REALSENSE_DEV_4:-/dev/null}"
      - "${REALSENSE_DEV_5:-/dev/null}:${REALSENSE_DEV_5:-/dev/null}"
      # Intel RealSense Camera IMU/HID Devices
      - "${REALSENSE_HID_0:-/dev/null}:${REALSENSE_HID_0:-/dev/null}"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
      - "${HOME}/.Xauthority:/root/.Xauthority:ro"
    device_cgroup_rules:
      - 'c *:* rmw'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, graphics]
    stdin_open: true
    tty: true
    networks:
      cpsl_net:
        ipv4_address: 192.168.1.42

networks:
  cpsl_net:
    name: cpsl_net
    driver: ipvlan
    driver_opts:
      parent: ${HOST_PARENT_INTERFACE:-eth0}
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
