services:
  cpsl_sensors:
    image: cpsl_sensors:cpu
    container_name: cpsl_sensors_dev_cpu
    ipc: host
    environment:
      - ROS_DOMAIN_ID=42
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
    ports:
      # TI Radar DCA1000 Streaming Port Forwarding
      - "4096:4096/udp"
      - "4098:4098/udp"
      # Livox Mid360 Lidar Port Forwarding
      - "56101:56101/udp"
      - "56201:56201/udp"
      - "56301:56301/udp"
      - "56401:56401/udp"
      # Ouster Lidar Port Forwarding
      - "7502:7502/udp"
      - "7503:7503/udp"
    devices:
      # TI Radars Serial Interfaces (Role Mapped)
      - "${FRONT_RADAR_CLI:-/dev/null}:${FRONT_RADAR_CLI:-/dev/null}"
      - "${FRONT_RADAR_DATA:-/dev/null}:${FRONT_RADAR_DATA:-/dev/null}"
      - "${BACK_RADAR_CLI:-/dev/null}:${BACK_RADAR_CLI:-/dev/null}"
      - "${BACK_RADAR_DATA:-/dev/null}:${BACK_RADAR_DATA:-/dev/null}"
      - "${DOWN_RADAR_CLI:-/dev/null}:${DOWN_RADAR_CLI:-/dev/null}"
      - "${DOWN_RADAR_DATA:-/dev/null}:${DOWN_RADAR_DATA:-/dev/null}"
      # Intel RealSense Camera Video Devices
      - "${REALSENSE_DEV_0:-/dev/null}:${REALSENSE_DEV_0:-/dev/null}"
      - "${REALSENSE_DEV_1:-/dev/null}:${REALSENSE_DEV_1:-/dev/null}"
      - "${REALSENSE_DEV_2:-/dev/null}:${REALSENSE_DEV_2:-/dev/null}"
      - "${REALSENSE_DEV_3:-/dev/null}:${REALSENSE_DEV_3:-/dev/null}"
      - "${REALSENSE_DEV_4:-/dev/null}:${REALSENSE_DEV_4:-/dev/null}"
      - "${REALSENSE_DEV_5:-/dev/null}:${REALSENSE_DEV_5:-/dev/null}"
      # Intel RealSense Camera IMU/HID Devices
      - "${REALSENSE_HID_0:-/dev/null}:${REALSENSE_HID_0:-/dev/null}"
      - source: "${REALSENSE_HID_1:-/dev/null}"
        target: "${REALSENSE_HID_1:-/dev/null}"
        permissions: rmw
      - source: "${REALSENSE_HID_2:-/dev/null}"
        target: "${REALSENSE_HID_2:-/dev/null}"
        permissions: rmw
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
      - "${HOME}/.Xauthority:/root/.Xauthority:ro"
      - "../:/workspace/CPSL_ROS2_Sensors"
    device_cgroup_rules:
      - 'c *:* rmw'
    stdin_open: true
    tty: true
