dataset_generator:
  ros__parameters:
    radar_enable: True
    lidar_enable: False
    lidar_topic: "livox/lidar"
    camera_enable: True
    camera_topic: "camera/cpsl_realsense/color/image_raw"
    camera_depth_enable: True
    camera_depth_topic: "camera/cpsl_realsense/depth/image_rect_raw"
    hand_tracking_enable: True
    hand_tracking_left_topic: "left_hand_joints"
    hand_tracking_right_topic: "right_hand_joints"
    imu_enable: False 
    imu_topic: "imu"
    vicon_enable: False
    vehicle_odom_enable: False
    vehicle_odom_topic: "odom"
    base_frame: "cpsl_realsense_color_optical_frame"
    frame_rate_save_data: 10.0 #5.0 for SAR, 20.0 for vel
    frame_rate_high_speed_sensors: 50.0
    dataset_path: "/home/cpsl/Downloads/datasets/hands_test_dataset_midlight"