dataset_generator:
  ros__parameters:
    radar_enable: True
    lidar_enable: False
    lidar_topic: "/cpsl_ugv_1/livox/lidar"
    camera_enable: True
    camera_topic: "/cpsl_ugv_1/camera/cpsl_realsense/color/image_raw"
    depth_enable: True
    depth_topic: "/cpsl_ugv_1/camera/cpsl_realsense/depth/image_rect_raw"
    realsense_enable: True
    imu_enable: False
    imu_topic: "imu"
    vicon_enable: False
    vehicle_odom_enable: False
    vehicle_odom_topic: "odom"
    base_frame: "cpsl_ugv_1/radar_0"
    frame_rate_save_data: 20.0 #5.0 for SAR, 20.0 for vel
    frame_rate_high_speed_sensors: 20.0
    dataset_path: "/home/cpsl/Downloads/datasets/all_motions_dataset"